name: Python UI Tests

on:
  push:
    branches: [ "feature_ui_tests" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests in parallel
      run: |
        pytest tests/ --alluredir=allure-results -n auto

    - name: Generate Allure report
      uses: simple-elf/allure-report-action@v1
      if: always()
      with:
        allure-results: allure-results
        allure-report: allure-report

    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: allure-report
        retention-days: 5

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/feature_ui_tests'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        keep_files: true
